```plantuml
@startuml
hide empty fields 
hide empty attributes 
hide empty methods
hide empty members
hide circle


class Titulacion 
class Aula 
class Asignatura 
class Examen 
class Profesor 

class Secretario
class Convocatoria 
class SolicitudVigilante  

Asignatura  "1..*" *-up-> "1" Titulacion : pertenece a 
Asignatura "1" --> "*" Examen
Asignatura "0..*" --> "1" Profesor

Profesor "1" -right-> "0..*" Asignatura : responsable de
Profesor "1" --> "0..*" Examen : responsable de

Examen "1.." -left-> "1" Convocatoria : corresponde a 

@enduml
```
