```plantuml
@startuml
hide empty fields 
hide empty attributes 
hide empty methods
hide empty members
hide circle

class Titulacion 
class Aula 
class Asignatura 
class Examen 
class Profesor 

class Secretario
class Convocatoria 
class Vigilancia  

Asignatura  "1..*" *--> "1" Titulacion : pertenece a 
Asignatura "1" --> "*" Examen

Profesor "1" --> "0..*" Asignatura : coordinador de 
Profesor "1" --> "0..*" Examen : responsable de

Examen "*" --> "1..*" Aula : se realiza en 
Examen "1.." --> "1" Vigilancia : requiere 

Vigilancia --> Secretario : validada por

@enduml
```
