@startuml
hide empty fields 
hide empty attributes 
hide empty methods
hide empty members
hide circle

class Alcalde
class Castigo
class Celda
class CentroPenitenciario
class Modulo
class Modulo_A extends Modulo
class Modulo_B extends Modulo
class Delito
class Preso
class Historial
class Condena
class Guardia
class Inspeccion
class Incidente
class Armas extends Incidente
class Drogas extends Incidente

@enduml
