```plantuml
@startuml
hide empty fields 
hide empty attributes 
hide empty methods
hide empty members
hide circle

class Servicio
class Trabajador
class Sanitario extends Trabajador
class Medico    extends Sanitario
class Enfermero extends Sanitario
class Cita
class Adicional extends Cita
class Medica    extends Cita
class Paciente

Paciente -right- Cita: solicita >
Servicio -down- Cita : recibe solicitd de > 
Trabajador -right- Servicio : trabaja en >


@enduml
```
